### PR TITLE
Introduce proper naming convention for model retraining

### PR DESCRIPTION
**Pull request by miteshvp**

### CODE REVIEW

**Comment by miteshvp** [comment]
`cyclomatic_complexity` failures are un-related. Ok to Merge cc @rootAvish

**Comment by miteshvp** [comment]
@tisnik - what is the way forward here? cyclomatic complexity failures are un-related to my changes. And I do not consider fixing those cyclomatic complexity is in-scope. cc @sivaavkd

**Comment by rootAvish** [comment]
[test]

**Comment by tisnik** [comment]
@miteshvp please look at https://github.com/fabric8-analytics/fabric8-analytics-npm-insights/pull/65 and if you merge it and rebase your PR, everything will be green again :) TYVM

**Comment by miteshvp** [comment]
Thanks Pavel. This helps.

**Pull request merged**
